#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollingService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MLODY")]
	public partial class SmartDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SmartDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MLODYConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SmartDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SmartDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SmartDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SmartDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User
	{
		
		private int _Id;
		
		private string _Name;
		
		private int _Age;
		
		private string _Parameter;
		
		private System.Nullable<byte> _Reading;
		
		private System.DateTime _ReadingTime;
		
		private System.Nullable<bool> _Monitored;
		
		private string _ActionToBeTaken;
		
		private System.Nullable<bool> _ActionTaken;
		
		private string _ActionDescription;
		
		public User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int NOT NULL")]
		public int Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parameter", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Parameter
		{
			get
			{
				return this._Parameter;
			}
			set
			{
				if ((this._Parameter != value))
				{
					this._Parameter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reading", DbType="TinyInt")]
		public System.Nullable<byte> Reading
		{
			get
			{
				return this._Reading;
			}
			set
			{
				if ((this._Reading != value))
				{
					this._Reading = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadingTime", DbType="DateTime NOT NULL")]
		public System.DateTime ReadingTime
		{
			get
			{
				return this._ReadingTime;
			}
			set
			{
				if ((this._ReadingTime != value))
				{
					this._ReadingTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monitored", DbType="Bit")]
		public System.Nullable<bool> Monitored
		{
			get
			{
				return this._Monitored;
			}
			set
			{
				if ((this._Monitored != value))
				{
					this._Monitored = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionToBeTaken", DbType="NVarChar(50)")]
		public string ActionToBeTaken
		{
			get
			{
				return this._ActionToBeTaken;
			}
			set
			{
				if ((this._ActionToBeTaken != value))
				{
					this._ActionToBeTaken = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionTaken", DbType="Bit")]
		public System.Nullable<bool> ActionTaken
		{
			get
			{
				return this._ActionTaken;
			}
			set
			{
				if ((this._ActionTaken != value))
				{
					this._ActionTaken = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionDescription", DbType="NVarChar(50)")]
		public string ActionDescription
		{
			get
			{
				return this._ActionDescription;
			}
			set
			{
				if ((this._ActionDescription != value))
				{
					this._ActionDescription = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
