<?xml version="1.0" encoding="utf-8"?><Database Name="MLODY" Class="SmartDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=KUSUMA439-PC;Initial Catalog=MLODY;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MLODYConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Parameter" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Reading" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="ReadingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Monitored" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ActionToBeTaken" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ActionTaken" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ActionDescription" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>